package com.sample.entity;

// Generated Dec 9, 2014 1:42:52 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Access generated by hbm2java
 */
@Entity
@Table(name = "access", catalog = "cqp_prime")
public class Access implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer employeeId;
	private Integer solutionGroupId;

	public Access() {
	}

	public Access(Integer employeeId, Integer solutionGroupId) {
		this.employeeId = employeeId;
		this.solutionGroupId = solutionGroupId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "EMPLOYEE_ID")
	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "SOLUTION_GROUP_ID")
	public Integer getSolutionGroupId() {
		return this.solutionGroupId;
	}

	public void setSolutionGroupId(Integer solutionGroupId) {
		this.solutionGroupId = solutionGroupId;
	}

}
