package com.sample.entity;

// Generated Dec 9, 2014 1:42:52 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bu generated by hbm2java
 */
@Entity
@Table(name = "bu", catalog = "cqp_prime")
public class Bu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String bu;
	private Set<Section> sections = new HashSet<Section>(0);

	public Bu() {
	}

	public Bu(String bu, Set<Section> sections) {
		this.bu = bu;
		this.sections = sections;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "bu", length = 3)
	public String getBu() {
		return this.bu;
	}

	public void setBu(String bu) {
		this.bu = bu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bu")
	public Set<Section> getSections() {
		return this.sections;
	}

	public void setSections(Set<Section> sections) {
		this.sections = sections;
	}

}
