package com.sample.entity;

// Generated Dec 9, 2014 1:42:52 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Holidays generated by hbm2java
 */
@Entity
@Table(name = "holidays", catalog = "cqp_prime")
public class Holidays implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Date holiday;
	private String description;

	public Holidays() {
	}

	public Holidays(Date holiday) {
		this.holiday = holiday;
	}

	public Holidays(Date holiday, String description) {
		this.holiday = holiday;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "HOLIDAY", nullable = false, length = 0)
	public Date getHoliday() {
		return this.holiday;
	}

	public void setHoliday(Date holiday) {
		this.holiday = holiday;
	}

	@Column(name = "DESCRIPTION", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
