package com.sample.entity;

// Generated Dec 9, 2014 1:42:52 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SmtSolutionGroup generated by hbm2java
 */
@Entity
@Table(name = "smt_solution_group", catalog = "cqp_prime")
public class SmtSolutionGroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String solutionGroupName;

	public SmtSolutionGroup() {
	}

	public SmtSolutionGroup(String solutionGroupName) {
		this.solutionGroupName = solutionGroupName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "SOLUTION_GROUP_NAME", length = 45)
	public String getSolutionGroupName() {
		return this.solutionGroupName;
	}

	public void setSolutionGroupName(String solutionGroupName) {
		this.solutionGroupName = solutionGroupName;
	}

}
