package com.sample.entity;

// Generated Dec 9, 2014 1:42:52 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SmtUserSolutionGroup generated by hbm2java
 */
@Entity
@Table(name = "smt_user_solution_group", catalog = "cqp_prime")
public class SmtUserSolutionGroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer userSolutionGroupId;
	private String email;
	private Integer solutionGroupId;

	public SmtUserSolutionGroup() {
	}

	public SmtUserSolutionGroup(String email, Integer solutionGroupId) {
		this.email = email;
		this.solutionGroupId = solutionGroupId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_SOLUTION_GROUP_ID", unique = true, nullable = false)
	public Integer getUserSolutionGroupId() {
		return this.userSolutionGroupId;
	}

	public void setUserSolutionGroupId(Integer userSolutionGroupId) {
		this.userSolutionGroupId = userSolutionGroupId;
	}

	@Column(name = "EMAIL", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "SOLUTION_GROUP_ID")
	public Integer getSolutionGroupId() {
		return this.solutionGroupId;
	}

	public void setSolutionGroupId(Integer solutionGroupId) {
		this.solutionGroupId = solutionGroupId;
	}

}
